name: Deploy Frontend
on:
  push:
    branches: [ "master", "main" ]  
  workflow_dispatch:                

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Build test image
        run: docker build -t theomerkaratas/docker-static-web-test -f Dockerfile.dev .
      - name: Run tests
        run: docker run -e CI=true theomerkaratas/docker-static-web-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-eu-west-1-895318998887
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: eu-west-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip